2019-10-19 12:19:02,446 ERROR: Exception on /gotinfo [GET] [in e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Google_Drive\3.Projects\0.LUAN_VAN\Embedded_Code\seperate_components\saveInfoServer\app\routes.py", line 46, in gotInfo
    func = request.environ.get('werkzeug.server.shutdown')
NameError: name 'request' is not defined
